spring:
    application:
        name: gavin-demo
    profiles:
        active: dev

server:
  port: 8082
#  ssl:
#    key-store: ./4310153_www.gavinhuang.cn.pfx
#    key-alias: tomcat
#    enabled: true
#    key-store-password: EidJ5dC9
#    key-store-type: PKCS12

logging:
  level:
    org.apache.zookeeper: ERROR
    kafka.admin: ERROR
    org.I0Itec.zkclient: ERROR
---


